# Generated by Django 3.1.12 on 2021-10-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Адресная книга', max_length=255)),
            ],
            options={
                'verbose_name': 'Адресная книга',
                'verbose_name_plural': 'Адресные книги',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
