# Generated by Django 3.1.12 on 2021-10-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_addressbook_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='status',
            new_name='is_active',
        ),
    ]
