# Generated by Django 3.1.12 on 2021-07-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letter",
            name="subtitle",
            field=models.CharField(
                default="Актуальные новости отрасли", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="letter",
            name="title",
            field=models.CharField(default="🐄 Новости животноводства", max_length=255),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
