# Generated by Django 3.1.12 on 2021-07-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_auto_20210702_2040"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
