# Generated by Django 3.1.12 on 2021-07-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, upload_to="img/news/thumbnails"),
        ),
    ]
