# Generated by Django 3.1.12 on 2021-07-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210705_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='news_long',
            field=models.ManyToManyField(related_name='news_long', through='news.LetterNewsLong', to='news.News'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='news_short',
            field=models.ManyToManyField(related_name='news_short', through='news.LetterNewsShort', to='news.News'),
        ),
    ]
