# Generated by Django 3.1.12 on 2021-07-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210705_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='news_long',
            field=models.ManyToManyField(related_name='_letter_news_long_+', through='news.LetterNewsLong', to='news.News'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='news_short',
            field=models.ManyToManyField(related_name='_letter_news_short_+', through='news.LetterNewsShort', to='news.News'),
        ),
    ]
