# Generated by Django 3.1.12 on 2021-07-06 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210705_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
