# Generated by Django 3.1.12 on 2022-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_journal_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='issue_type',
            field=models.CharField(choices=[('R', 'Номерной'), ('S', 'Тематический')], default='R', max_length=1, verbose_name='Тип выпуска'),
        ),
    ]
