# Generated by Django 3.1.12 on 2022-06-06 14:50

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_journal_issue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Рекламный баннер', max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='img/ad/banners')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламные баннеры',
            },
        ),
    ]
