# Generated by Django 3.1.12 on 2022-06-06 15:14

from django.db import migrations
import imagekit.models.fields
import zzr_mailer.content.models.advertisement_banner


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_advertisementbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementbanner',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=zzr_mailer.content.models.advertisement_banner.AdvertisementBanner.content_file_name),
        ),
    ]
