# Generated by Django 3.1.12 on 2021-11-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_announcement', '0002_auto_20211029_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueannouncementletter',
            old_name='synopsis',
            new_name='greeting',
        ),
    ]
