# Generated by Django 3.1.12 on 2021-11-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_announcement', '0003_auto_20211130_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueannouncementletter',
            name='greeting',
            field=models.TextField(verbose_name='Приветствие'),
        ),
    ]
