# Generated by Django 3.1.12 on 2021-10-26 12:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import letter.models.letter
import model_utils.fields
import news_digest.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_journal'),
        ('letter', '0003_auto_20211022_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Рекламный блок', max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Рекламный блок',
                'verbose_name_plural': 'Рекламные блоки',
            },
        ),
        migrations.CreateModel(
            name='IssueAnnouncementLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='🐄 Новости животноводства', max_length=255, verbose_name='Тема письма')),
                ('send_date', models.DateTimeField(default=news_digest.utils.next_monday, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('UNP', 'Не запланирована'), ('PND', 'Обработка...'), ('PLA', 'Запланирована'), ('SNT', 'Отправлена'), ('EXP', 'Просрочена'), ('ERR', 'Ошибка')], default='UNP', max_length=3, verbose_name='Статус')),
                ('synopsis', models.TextField(verbose_name='Встуление')),
                ('addressbooks', models.ManyToManyField(blank=True, default=letter.models.letter.get_active_addressbooks, to='letter.AddressBook', verbose_name='Адресные книги')),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issue_announcement.advertisement', verbose_name='Рекламный блок')),
            ],
            options={
                'verbose_name': 'Рассылочное письмо',
                'verbose_name_plural': 'Рассылочные письма',
            },
        ),
        migrations.CreateModel(
            name='LetterArticleShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_announcement.issueannouncementletter')),
            ],
            options={
                'verbose_name': 'Другая статья',
                'verbose_name_plural': 'Другие статьи',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='LetterArticleLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_announcement.issueannouncementletter')),
            ],
            options={
                'verbose_name': 'Статья с анонсом',
                'verbose_name_plural': 'Статьи с анонсом',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='issueannouncementletter',
            name='articles_long',
            field=models.ManyToManyField(related_name='_issueannouncementletter_articles_long_+', through='issue_announcement.LetterArticleLong', to='content.Article'),
        ),
        migrations.AddField(
            model_name='issueannouncementletter',
            name='articles_short',
            field=models.ManyToManyField(related_name='_issueannouncementletter_articles_short_+', through='issue_announcement.LetterArticleShort', to='content.Article'),
        ),
        migrations.AddField(
            model_name='issueannouncementletter',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='letter.Campaign'),
        ),
        migrations.AddField(
            model_name='issueannouncementletter',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.journal', verbose_name='Журнал'),
        ),
    ]
