# Generated by Django 3.1.12 on 2021-10-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_advertisement'),
        ('issue_announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueannouncementletter',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.advertisement', verbose_name='Рекламный блок'),
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
