# Generated by Django 3.1.12 on 2021-10-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressbook',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
    ]
