# Generated by Django 3.1.12 on 2022-02-11 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import zzr_mailer.letter.models.letter
import zzr_mailer.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_advertisement'),
        ('letter', '0004_auto_20220209_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAnnouncementLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='🐄 ', max_length=255, verbose_name='Тема письма')),
                ('send_date', models.DateTimeField(default=zzr_mailer.utils.utils.next_monday, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('UNP', 'Не запланирована'), ('PND', 'Обработка...'), ('PLA', 'Запланирована'), ('SNT', 'Отправлена'), ('EXP', 'Просрочена'), ('ERR', 'Ошибка')], default='UNP', max_length=3, verbose_name='Статус')),
                ('greeting', models.TextField(verbose_name='Приветствие')),
                ('addressbooks', models.ManyToManyField(blank=True, default=zzr_mailer.letter.models.letter.get_active_addressbooks, to='letter.AddressBook', verbose_name='Адресные книги')),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.advertisement', verbose_name='Рекламный блок')),
            ],
            options={
                'verbose_name': 'Анонс журнала',
                'verbose_name_plural': 'Анонсы журнала',
            },
        ),
        migrations.AlterModelOptions(
            name='newsdigestletter',
            options={'verbose_name': 'Новостной дайджест', 'verbose_name_plural': 'Новостные дайджесты'},
        ),
        migrations.CreateModel(
            name='LetterArticleShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.issueannouncementletter')),
            ],
            options={
                'verbose_name': 'Другая статья',
                'verbose_name_plural': 'Другие статьи',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='LetterArticleLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letter.issueannouncementletter')),
            ],
            options={
                'verbose_name': 'Статья с анонсом',
                'verbose_name_plural': 'Статьи с анонсом',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='issueannouncementletter',
            name='articles_long',
            field=models.ManyToManyField(related_name='_issueannouncementletter_articles_long_+', through='letter.LetterArticleLong', to='content.Article'),
        ),
        migrations.AddField(
            model_name='issueannouncementletter',
            name='articles_short',
            field=models.ManyToManyField(related_name='_issueannouncementletter_articles_short_+', through='letter.LetterArticleShort', to='content.Article'),
        ),
        migrations.AddField(
            model_name='issueannouncementletter',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='letter.Campaign'),
        ),
        migrations.AddField(
            model_name='issueannouncementletter',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.journal', verbose_name='Журнал'),
        ),
    ]
