# Generated by Django 3.1.12 on 2022-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0008_auto_20220406_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активная'),
        ),
    ]
