# Generated by Django 3.1.12 on 2022-06-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_advertisementbanner'),
        ('letter', '0009_auto_20220422_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdigestletter',
            name='advertisement_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.advertisementbanner', verbose_name='Рекламный баннер'),
        ),
    ]
