# Generated by Django 3.1.12 on 2022-06-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20220606_1514'),
        ('letter', '0010_newsdigestletter_advertisement_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueannouncementletter',
            name='advertisement_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.advertisementbanner', verbose_name='Рекламный баннер'),
        ),
    ]
