# Generated by Django 3.1.12 on 2023-11-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0012_auto_20231122_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericletter',
            name='campaign_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issueannouncementletter',
            name='campaign_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuedownloadletter',
            name='campaign_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsdigestletter',
            name='campaign_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
