# Generated by Django 3.1.12 on 2021-09-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '__first__'),
        ('content', '0001_initial'),
    ]

    operations = [
             migrations.RunSQL("""
            INSERT INTO content_news (
                created,
                modified,
                uuid,
                title,
                teaser,
                link,
                image,
                image_url,
                pub_date
            )
            SELECT
                created,
                modified,
                uuid,
                title,
                teaser,
                link,
                image,
                image_url,
                pub_date
            FROM
                news_digest_news;
        """, reverse_sql="""
            INSERT INTO news_digest_news (
                created,
                modified,
                uuid,
                title,
                teaser,
                link,
                image,
                image_url,
                pub_date
            )
            SELECT
                created,
                modified,
                uuid,
                title,
                teaser,
                link,
                image,
                image_url,
                pub_date
            FROM
                content_news;
        """)
    ]
