# Generated by Django 3.1.12 on 2021-10-26 10:42

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('link', models.URLField()),
                ('cover', imagekit.models.fields.ProcessedImageField(upload_to='img/journal/thumbnails')),
                ('cover_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
            },
        ),
    ]
