# Generated by Django 3.1.12 on 2021-10-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='created',
            field=models.DateField(null=True),
        ),
    ]
