# Generated by Django 3.1.12 on 2021-07-06 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='🐄 Новости животноводства', max_length=255)),
                ('subtitle', models.CharField(default='Актуальные новости отрасли', max_length=255)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('teaser', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='img/news/thumbnails')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LetterNewsShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_digest.letter')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_digest.news')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='LetterNewsLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_digest.letter')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_digest.news')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='news_long',
            field=models.ManyToManyField(related_name='_letter_news_long_+', through='news_digest.LetterNewsLong', to='news_digest.News'),
        ),
        migrations.AddField(
            model_name='letter',
            name='news_short',
            field=models.ManyToManyField(related_name='_letter_news_short_+', through='news_digest.LetterNewsShort', to='news_digest.News'),
        ),
    ]
