# Generated by Django 3.1.12 on 2021-08-02 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Рекламный блок', max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Рекламный блок',
                'verbose_name_plural': 'Рекламные блоки',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(default='🐄 Новости животноводства', max_length=255, verbose_name='Тема письма')),
                ('subtitle', models.CharField(default='Актуальные новости отрасли', max_length=255, verbose_name='Заголовок письма')),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('advertisement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_digest.advertisement', verbose_name='Рекламный блок')),
                ('campaign', models.ManyToManyField(blank=True, null=True, to='news_digest.Campaign')),
            ],
            options={
                'verbose_name': 'Рассылочное письмо',
                'verbose_name_plural': 'Рассылочные письма',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('teaser', models.TextField()),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, upload_to='img/news/thumbnails')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='LetterNewsShort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_digest.letter')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_digest.news')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='LetterNewsLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_digest.letter')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_digest.news')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='letter',
            name='news_long',
            field=models.ManyToManyField(related_name='_letter_news_long_+', through='news_digest.LetterNewsLong', to='news_digest.News'),
        ),
        migrations.AddField(
            model_name='letter',
            name='news_short',
            field=models.ManyToManyField(related_name='_letter_news_short_+', through='news_digest.LetterNewsShort', to='news_digest.News'),
        ),
    ]
