# Generated by Django 3.1.12 on 2021-08-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='campaign',
            new_name='campaigns',
        ),
        migrations.AddField(
            model_name='letter',
            name='addressbooks',
            field=models.ManyToManyField(blank=True, null=True, to='news_digest.AddressBook'),
        ),
    ]
