# Generated by Django 3.1.12 on 2021-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0002_auto_20210802_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbook',
            name='name',
            field=models.CharField(default='Адресная книга', max_length=255),
        ),
    ]
