# Generated by Django 3.1.12 on 2021-08-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0003_auto_20210802_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressbook',
            options={'verbose_name': 'Адресная книга', 'verbose_name_plural': 'Адресные книги'},
        ),
    ]
