# Generated by Django 3.1.12 on 2021-07-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0003_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_digest.advertisement')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_digest.letter')),
            ],
        ),
        migrations.AddField(
            model_name='letter',
            name='advertisement',
            field=models.ManyToManyField(related_name='_letter_advertisement_+', through='news_digest.LetterAdvertisement', to='news_digest.Advertisement'),
        ),
    ]
