# Generated by Django 3.1.12 on 2021-07-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0004_auto_20210707_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='Рекламный блок', max_length=255),
        ),
    ]
