# Generated by Django 3.1.12 on 2021-07-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0005_advertisement_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='advertisement',
        ),
        migrations.AddField(
            model_name='letter',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_digest.advertisement'),
        ),
        migrations.DeleteModel(
            name='LetterAdvertisement',
        ),
    ]
