# Generated by Django 3.1.12 on 2021-08-04 11:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0005_auto_20210804_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='addressbooks',
            field=models.ManyToManyField(blank=True, default=django.db.models.manager.BaseManager.all, null=True, to='news_digest.AddressBook'),
        ),
    ]
