# Generated by Django 3.1.12 on 2021-08-04 16:08

from django.db import migrations, models
import django.db.models.manager
import news_digest.utils


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0006_auto_20210804_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letternewslong',
            options={'ordering': ('order',), 'verbose_name': 'Новость с анонсом', 'verbose_name_plural': 'Новости с анонсом'},
        ),
        migrations.AlterModelOptions(
            name='letternewsshort',
            options={'ordering': ('order',), 'verbose_name': "Новость 'Одной строкой'", 'verbose_name_plural': "Новости 'Одной строкой'"},
        ),
        migrations.AlterField(
            model_name='letter',
            name='addressbooks',
            field=models.ManyToManyField(blank=True, default=django.db.models.manager.BaseManager.all, null=True, to='news_digest.AddressBook', verbose_name='Адресные книги'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='send_date',
            field=models.DateTimeField(default=news_digest.utils.next_monday, verbose_name='Дата отправки'),
        ),
    ]
