# Generated by Django 3.1.12 on 2021-08-09 12:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0008_auto_20210806_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('UNP', 'Unplanned'), ('PND', 'Pending'), ('PLA', 'Planned')], default='UNP', max_length=3),
        ),
        migrations.AlterField(
            model_name='letter',
            name='addressbooks',
            field=models.ManyToManyField(blank=True, default=django.db.models.manager.BaseManager.all, null=True, to='news_digest.AddressBook', verbose_name='Адресные книги'),
        ),
    ]
