# Generated by Django 3.1.12 on 2021-08-11 17:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0011_auto_20210811_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='addressbooks',
            field=models.ManyToManyField(blank=True, default=django.db.models.manager.BaseManager.all, to='news_digest.AddressBook', verbose_name='Адресные книги'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='campaigns',
            field=models.ManyToManyField(blank=True, to='news_digest.Campaign'),
        ),
    ]
