# Generated by Django 3.1.12 on 2021-08-12 16:20

from django.db import migrations, models
import django.db.models.manager
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0013_auto_20210811_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='addressbooks',
            field=models.ManyToManyField(blank=True, default=django.db.models.manager.BaseManager.all, to='news_digest.AddressBook', verbose_name='Адресные книги'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='img/news/thumbnails'),
        ),
    ]
