# Generated by Django 3.1.12 on 2021-09-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_digest', '0016_auto_20210907_1636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
